name: Telemetry

on:
  pull_request:
    branches:
      - master
    paths:
      - "telemetry-web/**"
  push:
    branches:
      - master
    paths:
      - "telemetry-web/**"
  workflow_dispatch:

env:
  GOLANG_CI_LINT_VERSION: v2.12.2

jobs:
  validate:
    name: Validate telemetry
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Validate telemetry
        uses: ./telemetry-web/.github/actions/validate
        with:
          golangci-lint-version: ${{ env.GOLANG_CI_LINT_VERSION }}
